"""Modificando o atributo unique de nome para cpf no modelo atleta

Revision ID: 2d6d48b0fac2
Revises: a23bbc97058a
Create Date: 2024-07-05 21:25:26.667843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6d48b0fac2'
down_revision: Union[str, None] = 'a23bbc97058a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atletas_nome_key', 'atletas', type_='unique')
    op.create_unique_constraint(None, 'atletas', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='unique')
    op.create_unique_constraint('atletas_nome_key', 'atletas', ['nome'])
    # ### end Alembic commands ###
